### PR TITLE
Change background colour to red

### PR DESCRIPTION
**Pull request by twilkinson573**
- [x] Change the colour text on the home page

That's it for now

### CODE REVIEW

**Comment by flehodey** [comment]
hello, looks alright !

**Comment by twilkinson573** [comment]
Hmm I was thinking about adding something like this:

```
body { 
  color: red
  text-align: center
}
```

**Comment by umersaqib160** [comment]
good work. push it :)

**Comment by twilkinson573** [comment]
@umersaqib160 the front end genius thinks it's good, let's merge!

**Pull request merged**
